image: thomasjpfan/numpy-gitpod
tasks:
  # The base image complied numpy with ccache enabled. This second build
  # should be faster since it is using the cache.
  - init: |
      python setup.py build_ext -i
      echo "export PYTHONPATH=$PWD" >> ~/.bashrc
      source ~/.bashrc
    command: python -c "import numpy; print(numpy.__path__)"

github:
  prebuilds:
    master: true
    branches: true
